###################  Microservice base configuration  ###################
spring.application:
  name: expense-tracker
  version: 0.0.1-SNAPSHOT
  environment: ${ENV}

server:
  port: 8080
  ssl.enabled: false # disable https
  servlet.context-path: /${spring.application.name}

logging.level:
  root: INFO
  org.springframework: INFO
  com.portfolio: INFO

springdoc:
  api-docs.path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method


###################  MongoDB configuration  ###################
spring.data.mongodb:
  uri: SECRET_MONGODB_ENDPOINT
  auto-index-creation: true

###################  Authentication and Authorization  ###################
auth.enabled: true
auth.jwt.secret: SECRET_AUTH_SECRET