###################  Microservice base configuration  ###################
spring.application.environment: local

server.port: 8080


###################  Authentication and Authorization  ###################
auth.enabled: true
auth.jwt.secret: 0SnXhfnVgPK0EZRWfr3tV3NGDvHacT1mSg6ziXtoWhdVdhV5msi7oHDspXAqg5Bx
# Jwt Example: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzU2ODk1OTksInN1YiI6IkNoaWNvIiwiZGlnaXRhbFVzZXJJZCI6IjRmMTE4ODY4LTE2ODQtNDc5My1hOTFjLWRjMGUxZWM1N2UzNCIsImlhdCI6MTcyNTY5OTYxOCwiaXNzIjoiYXV0aDgiLCJhdWQiOlsiZXhwZW5zZS10cmFja2VyIiwicG9ydGZvbGlvLW1hbmFnZXIiXSwic2NvcGUiOiJESUdJVEFMX1VTRVJfQ1JFQVRFIn0.cjT2OfvEZKiHOeYcmWyYI1MZhhJCUOqR-HWofOaMix3dZLIne5WKiMSrB-QpCybtmFCAfxgocwWPfAAk40AZKQ


###################  MongoDB configuration  ###################
spring.data.mongodb.uri: mongodb://localhost:27017/ExpenseTracker


###################  Data Provider REST configuration  ###################
http.url:
  portfolio-manager: "http://localhost:3000/portfolio-manager/api/v1"